// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview An AI tool that suggests relevant question types and adjustments to a form based on the target audience and purpose.
 *
 * - formTailor - A function that suggests form adjustments.
 * - FormTailorInput - The input type for the formTailor function.
 * - FormTailorOutput - The return type for the formTailor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FormTailorInputSchema = z.object({
  formPurpose: z
    .string()
    .describe('The purpose of the form, e.g., customer feedback, employee survey.'),
  targetAudience: z
    .string()
    .describe('The target audience for the form, e.g., students, professionals, general public.'),
  existingQuestions: z
    .string()
    .describe('The existing questions in the form, if any.'),
});
export type FormTailorInput = z.infer<typeof FormTailorInputSchema>;

const FormTailorOutputSchema = z.object({
  suggestedQuestionTypes: z
    .string()
    .describe('Suggested question types relevant to the form purpose and target audience.'),
  suggestedAdjustments: z
    .string()
    .describe('Suggested adjustments to the existing questions or form structure.'),
});
export type FormTailorOutput = z.infer<typeof FormTailorOutputSchema>;

export async function formTailor(input: FormTailorInput): Promise<FormTailorOutput> {
  return formTailorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'formTailorPrompt',
  input: {schema: FormTailorInputSchema},
  output: {schema: FormTailorOutputSchema},
  prompt: `You are an AI assistant that helps form creators tailor their forms for better results.

  Based on the form's purpose, target audience, and existing questions, you will suggest relevant question types and adjustments.

  Form Purpose: {{{formPurpose}}}
  Target Audience: {{{targetAudience}}}
  Existing Questions: {{{existingQuestions}}}

  Provide suggestions for question types and adjustments to make the form more effective for the specified target audience and purpose.
  `,
});

const formTailorFlow = ai.defineFlow(
  {
    name: 'formTailorFlow',
    inputSchema: FormTailorInputSchema,
    outputSchema: FormTailorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
